- name: Setup
  hosts: localhost
  tasks:
    - name: Install fish
      community.general.homebrew:
        name: fish
    - name: Set fish shell
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /opt/homebrew/bin/fish
    - name: Create fish directory
      ansible.builtin.file:
        mode: u=rwx,g=rx,o=rx
        path: ~/.config/fish
        state: directory
    - name: Add Homebrew to PATH
      ansible.builtin.lineinfile:
        create: true
        line: eval "$(/opt/homebrew/bin/brew shellenv)"
        mode: u=rw,g=r,o=r
        path: ~/.config/fish/config.fish

    # Install
    - name: Install Homebrew formula
      community.general.homebrew:
        name: "{{ item }}"
      loop:
        - mise
        - neovim
        - tldr

    - name: Install Homebrew cask
      community.general.homebrew_cask:
        name: "{{ item }}"
      loop:
        - arc
        - jetbrains-toolbox
        - raycast

    - name: Install Node.js
      ansible.builtin.command: mise use --global node@20
      register: node
      changed_when: "'installed' in node.stderr"

    - name: Install pnpm
      ansible.builtin.command: mise use --global pnpm --yes
      register: pnpm
      changed_when: "'installed' in pnpm.stderr"

    # Configure
    - name: Tap to click
      community.general.osx_defaults:
        domain: com.apple.AppleMultitouchTrackpad
        key: Clicking
        type: int
        value: 1

    - name: Automatically hide and show the Dock
      community.general.osx_defaults:
        domain: com.apple.dock
        key: autohide
        type: bool
        value: true
    - name: Show suggested and recent apps in Dock
      community.general.osx_defaults:
        domain: com.apple.dock
        key: show-recents
        type: bool
        value: false

    - name: Show all filename extensions
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: AppleShowAllExtensions
        type: bool
        value: true
    - name: Show path bar
      community.general.osx_defaults:
        domain: com.apple.finder
        key: ShowPathbar
        type: bool
        value: true

    - name: Generate SSH key
      community.crypto.openssh_keypair:
        path: ~/.ssh/id_ed25519
        type: ed25519

    - name: Configure ~/.gitconfig
      community.general.git_config:
        name: "{{ item.name }}"
        scope: global
        value: "{{ item.value }}"
      loop:
        - name: user.name
          value: "Bastien Sun"
        - name: user.email
          value: "43788700+bastiensun@users.noreply.github.com"
        - name: core.editor
          value: "nvim"

        - name: gpg.format
          value: "ssh"
        - name: user.signingkey
          value: "~/.ssh/id_ed25519.pub"
        - name: commit.gpgsign
          value: "true"
