- name: Setup
  hosts: localhost
  tasks:
    - name: Install fish
      community.general.homebrew:
        name: fish
    - name: Set fish shell
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /opt/homebrew/bin/fish
    - name: Create fish directory
      ansible.builtin.file:
        mode: u=rwx,g=rx,o=rx
        path: ~/.config/fish
        state: directory
    - name: Add Homebrew to PATH
      ansible.builtin.blockinfile:
        block: |
          eval "$(/opt/homebrew/bin/brew shellenv)"
          starship init fish | source
        create: true
        mode: u=rw,g=r,o=r
        path: ~/.config/fish/config.fish

    # Install
    - name: Install Homebrew formula
      community.general.homebrew:
        name: "{{ item }}"
      loop:
        - act
        - mise
        - mole
        - starship
        - tldr

    - name: Install Homebrew cask
      community.general.homebrew_cask:
        name: "{{ item }}"
      loop:
        - brave-browser
        - discord
        - docker
        - ghostty
        - homerow
        - nikitabobko/tap/aerospace
        - obsidian
        - raycast
        - signal
        - ubersicht
        - zed
        - zoom

    # Configure
    - name: Tap to click
      community.general.osx_defaults:
        domain: com.apple.AppleMultitouchTrackpad
        key: Clicking
        type: int
        value: 1

    - name: Automatically hide and show the Dock
      community.general.osx_defaults:
        domain: com.apple.dock
        key: autohide
        type: bool
        value: true
    - name: Show suggested and recent apps in Dock
      community.general.osx_defaults:
        domain: com.apple.dock
        key: show-recents
        type: bool
        value: false

    - name: Automatically hide the menu bar
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: _HIHideMenuBar
        type: bool
        value: true
    - name: Show all filename extensions
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: AppleShowAllExtensions
        type: bool
        value: true
    - name: Show path bar
      community.general.osx_defaults:
        domain: com.apple.finder
        key: ShowPathbar
        type: bool
        value: true

    - name: Show battery percentage in the menu bar
      community.general.osx_defaults:
        domain: com.apple.controlcenter
        host: currentHost
        key: BatteryShowPercentage
        type: bool
        value: true

    - name: Generate SSH key
      community.crypto.openssh_keypair:
        path: ~/.ssh/id_ed25519
        type: ed25519

    - name: Configure ~/.gitconfig
      community.general.git_config:
        name: "{{ item.name }}"
        scope: global
        value: "{{ item.value }}"
      loop:
        - name: user.name
          value: "Bastien Sun"
        - name: user.email
          value: "43788700+bastiensun@users.noreply.github.com"
        - name: core.editor
          value: "zed"

        - name: gpg.format
          value: "ssh"
        - name: user.signingkey
          value: "~/.ssh/id_ed25519.pub"
        - name: commit.gpgsign
          value: "true"

    - name: Create Ghostty directory
      ansible.builtin.file:
        mode: u=rwx,g=rx,o=rx
        path: ~/.config/ghostty
        state: directory
    - name: Configure Ghostty
      ansible.builtin.blockinfile:
        block: |
          theme = dark:Catppuccin Mocha,light:Catppuccin Latte
        create: true
        mode: u=rw,g=r,o=r
        path: ~/.config/ghostty/config

    - name: Create AeroSpace directory
      ansible.builtin.file:
        mode: u=rwx,g=rx,o=rx
        path: ~/.config/aerospace
        state: directory
    - name: Copy AeroSpace config
      ansible.builtin.copy:
        dest: ~/.config/aerospace/aerospace.toml
        mode: u=rw,g=r,o=r
        src: ./dotfiles/aerospace.toml

    - name: Configure simple-bar
      ansible.builtin.git:
        repo: https://github.com/Jean-Tinland/simple-bar.git
        dest: "~/Library/Application\ Support/Übersicht/widgets/simple-bar"
        version: "HEAD" # noqa: latest
    - name: Copy simple-bar config
      ansible.builtin.copy:
        dest: ~/.simplebarrc
        mode: u=rw,g=r,o=r
        src: ./dotfiles/simple-bar.json

    - name: Copy Zed config
      ansible.builtin.copy:
        dest: ~/.config/zed
        mode: u=rw,g=r,o=r
        src: ./dotfiles/zed.json
