name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * 0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ansible/ansible-lint@v24

  integration:
    name: Integration
    runs-on: macos-12
    steps:
      # Uninstall runner preinstalled software
      - run: rm -rf ~/.yarn
      - run: brew uninstall firefox
      - run: brew uninstall maven
      - run: brew uninstall --ignore-dependencies node
      - run: sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"

      - uses: actions/checkout@v4
      - run: pip3 install --requirement requirements.txt
      - run: ansible-galaxy install --role-file requirements.yml
      - run: ansible-playbook --syntax-check playbook.yml
      - run: ansible-playbook ${RUNNER_DEBUG:+-vvv} playbook.yml
        env:
          ANSIBLE_FORCE_COLOR: true
      - name: Idempotence check
        run: |
          idempotence=$(mktemp)
          ansible-playbook ${RUNNER_DEBUG:+-vvv} playbook.yml | tee -a ${idempotence}
          tail ${idempotence} | grep --quiet 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
        env:
          ANSIBLE_FORCE_COLOR: true
